application: click-tracker-1301
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: admin_api.main.api

- url: /.*
  script: tracker_api.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: 2.6
- name: endpoints
  version: 1.0